name: VibeTravels CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch: # Pozwala na ręczne uruchomienie

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.nvmrc.outputs.node-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read .nvmrc
        id: nvmrc
        run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run unit tests
        run: npm test

  build:
    name: Build
    needs: [setup, lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env.test file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env.integration
          echo "E2E_USERNAME=${{ secrets.E2E_USERNAME }}" >> .env.integration
          echo "E2E_USERNAME_ID=${{ secrets.E2E_USERNAME_ID }}" >> .env.integration
          echo "E2E_PASSWORD=${{ secrets.E2E_PASSWORD }}" >> .env.integration
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env.integration
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY || secrets.SUPABASE_KEY }}" >> .env.integration

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 7

  deploy:
    name: Deploy
    needs: [setup, build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vibetravels:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/vibetravels:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/vibetravels:buildcache,mode=max
          build-args: |
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/vibetravels:latest
            docker stop vibetravels || true
            docker rm vibetravels || true
            docker run -d --name vibetravels -p 80:80 \
              -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
              -e SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
              -e OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
              ${{ secrets.DOCKER_USERNAME }}/vibetravels:latest
